# Generated by Django 5.2.8 on 2025-11-26 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(db_index=True, max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('url', models.CharField(blank=True, max_length=300)),
                ('named_url', models.CharField(blank=True, max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tree_menu.menuitem')),
            ],
            options={
                'ordering': ['parent_id', 'id'],
            },
        ),
    ]
